### ISSUE TITLE
Idealized payout when your baker has over 100% efficiency

### ISSUE THREAD

**Issue by gaia** [cryptiumlabs/backerei#8]
I understand idealized payouts will pay as if my baker filled 100% of its endorsements and backing slots.

But if my baker steals endorsements/bakes in addition to all the ones originally scheduled, does backerei pay out above what it would payout at 100% efficiency?

**Comment by cwgoes** [comment]
Endorsements cannot be stolen. Backerei *does not* presently pay stolen blocks (in line with the idealized payout schedule, stolen blocks are paid wholly to the baker). Backerei *does* pay realized transaction fees (since they cannot be predicated ahead of time). 

Configuration options supporting different payout strategies would be great additions, and we'd be happy to review/merge. Idealized payouts are more complicated than realized ones; you could easily update the [calculateRewards function](https://github.com/cryptiumlabs/backerei/blob/master/app/Payout.hs#L120) to pay exactly what your baker actually made (less fees).

**Comment by gaia** [comment]
Thanks Chris. I will look further into this and see if I can send a PR.
